### ISSUE TITLE
Initial release checklist

### ISSUE THREAD

**Issue by trentmwillis** [ember-engines/babel-plugin-compact-reexports#2]
- [x] Add tests for module options (loose, strict, noInterop)
- [x] Confirm Ember-CLI default re-exports work as expected
- [x] Add end-to-end smoke test
- [x] Setup ESLint
- [x] Setup code coverage
- [x] Verify integration with ember-engines
